language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jms0324/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jms0324/react-test-app npm test

after_success:
  - docker build -t jms0324/docker-frontend ./frontend
  - docker build -t jms0324/docker-backend ./backend
  - docker build -t jms0324/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jms0324/docker-frontend
  - docker push jms0324/docker-backend
  - docker push jms0324/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full-stack-2"
  env: "Dockerfullstack2-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-250058502806
  bucket_path: "docker-full-stack-2"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY